spring:
  application:
    name: medicalService
  config:
    import: optional:secrets.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/medicalService?stringtype=unspecified
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: db/migration
  security:
    jwt:
      secret: 399BEE1BFDA3DBC36BDDF873D3D81FD3548C5D6354DAE109DF9490D2F92405B3
      expiration: PT12H
  mail:
    host: smtp.gmail.com
    port: 587
    username: # Replace with mail service
    password: # Replace with password for mail service
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML
app:
  feign:
    config:
      name: openFDA
      url: https://api.fda.gov
  scheduled:
    cron: '0 0 8 * * ?'
  email:
    subject: 'Прием у врача. Напоминание'
    template: mail-template

client:
  payment:
    service:
      url: http://localhost:8081
